import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Table from '@mui/material/Table';
import TableBody from '@mui/material/TableBody';
import TableCell from '@mui/material/TableCell';
import TableContainer from '@mui/material/TableContainer';
import TableHead from '@mui/material/TableHead';
import TableRow from '@mui/material/TableRow';
import Paper from '@mui/material/Paper';
import {useEffect, useState} from "react";

const Home: NextPage = () => {
    function createData(
        name: string,
        invested: number,
        date: string,
        tokensNumber: number,
        share: string,
    ) {
        return { name, invested, date, tokensNumber, share };
    }

    const [rate, setRate] = useState<any>(null);

    const getRate = async () => {
        const rate = await fetch("/api/hello")
        const data = await rate.json();
        setRate(data);
    }
    const rows = [
        createData('MilkyWayEx', 120, "16.11.2021", 500000, '50/50'),
    ];

    useEffect(() => {
        getRate();
    }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Dex invest</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <h1>Dex invest</h1>
      <main className={styles.main}>
          <h2>Noa - Neakname investment pool</h2>
          <TableContainer component={Paper}>
              <Table sx={{ minWidth: 650 }} aria-label="simple table">
                  <TableHead>
                      <TableRow>
                          <TableCell>Project</TableCell>
                          <TableCell align="right">Invested $</TableCell>
                          <TableCell align="right">Total tokens</TableCell>
                          <TableCell align="right">Invested date</TableCell>
                          <TableCell align="right">Share</TableCell>
                          <TableCell align="right">Current value</TableCell>
                      </TableRow>
                  </TableHead>
                  <TableBody>
                      {rows.map((row) => (
                          <TableRow
                              key={row.name}
                              sx={{ '&:last-child td, &:last-child th': { border: 0 } }}
                          >
                              <TableCell component="th" scope="row">
                                  {row.name}
                              </TableCell>
                              <TableCell align="right">{row.invested}</TableCell>
                              <TableCell align="right">{row.tokensNumber}</TableCell>
                              <TableCell align="right">{row.date}</TableCell>
                              <TableCell align="right">{row.share}</TableCell>
                              <TableCell align="right">{rate && rate.data && row.tokensNumber * rate.data[14545].quote.USD.price}</TableCell>
                          </TableRow>
                      ))}
                  </TableBody>
              </Table>
          </TableContainer>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
